version: '3.8'

services:
  # WhatsAI Application
  whatsai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsai-manager
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
      PORT: 5173
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-https://hsapi.studio/}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-your-evolution-api-key}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      DATABASE_URL: file:./data/dev.db
    volumes:
      # Persist SQLite database
      - ./prisma/data:/app/prisma/data
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - whatsai-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL Database (if you want to migrate from SQLite)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: whatsai-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-whatsai}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-whatsai_password}
  #     POSTGRES_DB: ${POSTGRES_DB:-whatsai}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - whatsai-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whatsai}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # Optional: Evolution API (if you want to run it locally)
  # evolution-api:
  #   image: atendai/evolution-api:latest
  #   container_name: evolution-api
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SERVER_URL: http://localhost:8080
  #     AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY:-your-evolution-api-key}
  #   volumes:
  #     - evolution-data:/evolution/instances
  #   networks:
  #     - whatsai-network

networks:
  whatsai-network:
    driver: bridge

volumes:
  # postgres-data:
  # evolution-data:
  whatsai-data:
